### ISSUE TITLE
Did you consider UTF8 instead of VarUInt

### ISSUE THREAD

**Issue by marler8997** [TinyVG/specification#1]
I'm reading the specification and was curious if you considered using UTF8 rather than a custom integer encoding?  If so, what are your thoughts?  If not, do you think using UTF8 might be a good alternative?

**Comment by ikskuh** [comment]
UTF-8 has a not-as-tight encoding, but allows detection of in-stream data.

This makes sense for text, but not for a fixed binary format where you cannot decipher if you're in the file or at the beginning. The current encoding is more compact, as it doesn't require this feature.

**Comment by marler8997** [comment]
Ah yes that's true. Thanks for your thoughts.
