### ISSUE TITLE
[Proposal] Group opacity, or more generally compositing

### ISSUE THREAD

**Issue by rsheeter** [TinyVG/specification#10]
IIUC (as ever, apologies if this is simply a reader error) tinyvg will have trouble matching svgs that assign opacity to a group, similar to those described in https://github.com/googlefonts/picosvg/issues/78.

More broadly, no mechanism for compositing and blending appears to be provided.

Arguably this is by design :)

**Comment by ikskuh** [comment]
Yes, this is by design. Shapes are stored in a linear list and not in a hierarchical structure. This will not change, as it can be implemented via tools and is not required to be part of the format
