### ISSUE TITLE
[Clarification] Coordinate system for gradient control points

### ISSUE THREAD

**Issue by neinseg** [TinyVG/specification#12]
For gradient fills, the spec talks about start and end points. I think it is implied that these points are in absolute coordinates. I think the spec should explicitly state that, because relative coordinates would also make sense in this context.

**Comment by ikskuh** [comment]
Ah yes, good point. All coordinates in TinyVG are absolute

**Comment by ikskuh** [comment]
Fixed in the intro note section by saying that all coordinates are absolute
